pleroma: use beam 27
Not compatible with OTP 28
== Compilation error in file lib/open_api_spex/cast_parameters.ex ==
** (ArgumentError) cannot inject attribute @default_parsers into
function/macro because cannot escape
lists, tuples, maps, atoms, numbers, bitstrings, PIDs and remote
functions in the format &Mod.fun/arity
    (elixir 1.18.4) lib/kernel.ex:3777: Kernel.do_at_escape/2
    (elixir 1.18.4) expanding macro: Kernel.@/1
    lib/open_api_spex/cast_parameters.ex:123:
OpenApiSpex.CastParameters.cast_location/6
could not compile dependency :open_api_spex, "mix compile" failed.
Errors may have been logged above. You can recompile this dependency
with "mix deps.compile open_api_spex --force", update it with "mix
deps.update open_api_spex" or clean it with "mix deps.clean
open_api_spex"